@URL = http://localhost:8802

# SignIn을 통해 나온 AccessToken을 아래에 적어 주세요.
@ACCESS_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6Ik1FTUJFUiIsImdyYWRlIjoiR0VORVJBTCIsImlhdCI6MTYzNjkzNDc1MCwiZXhwIjoxNjM2OTM4MzUwfQ.GnvrTDxChNDmye89MYDOF720751WnmjtTNrpF3MSRH4

###
GET {{URL}}
Content-Type: application/json

{
    
}

###
POST {{URL}}/auth/sign-up
Content-Type: application/json

{
    "email": "user@user.com",
    "password": "user"
}

###
#해당 API 실행 후 나오는 access token을 위변수에 넣어 주세요 (유저 access token)
POST {{URL}}/auth/sign-in
Content-Type:  application/json

{
    "email": "user@user.com",
    "password": "user"
}


###
#해당 API 실행 후 나오는 access token을 위변수에 넣어 주세요 (관리자 access token)
POST {{URL}}/auth/sign-in
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "admin"
}

###
#user관련 API는 관리자만 접근 가능합니다.
GET {{URL}}/users
Content-Type: application/json
Authorization: bearer {{ACCESS_TOKEN}}

{

}

###
GET {{URL}}/users/2
Content-Type: application/json
Authorization: bearer {{ACCESS_TOKEN}}

{

}

###
PATCH  {{URL}}/users/2
Content-Type: application/json
Authorization: bearer {{ACCESS_TOKEN}}

{
    "grade": "IMPORTANT"
}

###
DELETE {{URL}}/users/2
Content-Type: application/json
Authorization: bearer {{ACCESS_TOKEN}}

{

}

###
GET {{URL}}/products
Content-Type: application/json
Authorization: bearer {{ACCESS_TOKEN}}

{

}

###
GET {{URL}}/products/1
Content-Type: application/json
Authorization: bearer {{ACCESS_TOKEN}}

{

}

###
POST  {{URL}}/products
Content-Type: application/json
Authorization: bearer {{ACCESS_TOKEN}}

{
    "productName":  "상품 5",
    "productPrice": "250000",
    "productStock": 5,
    "allowGrade" : "IMPORTANT",
    "discountRate": 3.2
}



###
PATCH  {{URL}}/products/1
Content-Type: application/json
Authorization: bearer {{ACCESS_TOKEN}}

{
    "productName": "품상 1"
}

###
DELETE  {{URL}}/products/1
Content-Type: application/json
Authorization: bearer {{ACCESS_TOKEN}}

{

}



