version: "3.7"
services:
  db:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    container_name: lawlabs_db
    ports:
      - "8801:3306"
    environment:
      - MYSQL_DATABASE=assignment_db
      - MYSQL_ROOT_PASSWORD=test-db 
      - TZ=Asia/Seoul

    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./database:/var/lib/mysql